<?php  
if(!isset($_REQUEST['id'])){
    header("Location: index.php");
}   
include_once('OAuth.php');
include_once('includes/init.php');

$query = $db->query("SELECT * FROM orders WHERE id=(SELECT MAX(id) FROM orders)");
$sql = mysqli_fetch_assoc($query);
//echo $sql['id'];
//echo $sql['total_price'];
//pesapal params
$token = $params = NULL;
 

/*
PesaPal Sandbox is at http://demo.pesapal.com. Use this to test your developement and 
when you are ready to go live change to https://www.pesapal.com.
*/
$consumer_key = 't7ULffCf9h25Yns972SG6V/UfKpaFIuV';//Register a merchant account on
                   //demo.pesapal.com and use the merchant key for testing.
                   //When you are ready to go live make sure you change the key to the live account
                   //registered on www.pesapal.com!
$consumer_secret = 'sSeyXIUQtKvwBZpNUxH2GgMZfTQ=';// Use the secret from your test
                   //account on demo.pesapal.com. When you are ready to go live make sure you 
                   //change the secret to the live account registered on www.pesapal.com!
$signature_method = new OAuthSignatureMethod_HMAC_SHA1();
$iframelink = 'http://demo.pesapal.com/api/PostPesapalDirectOrderV4';//change to      
                   //https://www.pesapal.com/API/PostPesapalDirectOrderV4 when you are ready to go live!

//get form details
$amount = $sql['total_price']; //$_POST['amount'];
$amount = number_format($amount, 2);//format amount to 2 decimal places

$desc = 'One two three'; //$_POST['description'];
$type = 'MERCHANT';
$reference = $_GET['id'];//unique order id of the transaction, generated by merchant
$first_name = 'Abel';//$_POST['firstname'];
$last_name =  'Wasike';//$_POST['lastname'];
$email = 'abellwasike@gmail.com';//$_POST['email'];
$phonenumber = '';//$_POST['number'];//ONE of email or phonenumber is required

$callback_url = 'http://copy/orderSuccess.php'; //redirect url, the page that will handle the response from pesapal.

$post_xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><PesapalDirectOrderInfo xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Amount=\"".$amount."\" Description=\"".$desc."\" Type=\"".$type."\" Reference=\"".$reference."\" FirstName=\"".$first_name."\" LastName=\"".$last_name."\" Email=\"".$email."\" PhoneNumber=\"".$phonenumber."\" xmlns=\"http://www.pesapal.com\" />";
$post_xml = htmlentities($post_xml);

$consumer = new OAuthConsumer($consumer_key, $consumer_secret);

//post transaction to pesapal
$iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, "GET", $iframelink, $params);
$iframe_src->set_parameter("oauth_callback", $callback_url);
$iframe_src->set_parameter("pesapal_request_data", $post_xml);
$iframe_src->sign_request($signature_method, $consumer, $token);

//display pesapal - iframe and pass iframe_src
?>
<!DOCTYPE html>
<html lang="en">
<head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  <link rel="shortcut icon" type="image/png" href="billsblack.png"/>
    <title>Order Success</title>
    <meta charset="utf-8">
    <style>
	body{background-color: rgb(234,237,237);}
    .container{width: 100%;padding: 50px;}
    p{color: #34a853;font-size: 18px;}
    footer{
  position: fixed;
  bottom: 0;
}

@media (max-height:800px){
  footer { position: static; }
  header { padding-top:40px; }
}


.footer-distributed{
  background-color: #2c292f;
  box-sizing: border-box;
  width: 100%;
  text-align: left;
  font: bold 16px sans-serif;
  padding: 50px 50px 60px 50px;
  margin-top: 80px;
}

.footer-distributed .footer-left,
.footer-distributed .footer-center,
.footer-distributed .footer-right{
  display: inline-block;
  vertical-align: top;
}

/* Footer left */

.footer-distributed .footer-left{
  width: 30%;
}

.footer-distributed h3{
  color:  #ffffff;
  font: normal 36px 'Cookie', cursive;
  margin: 0;
}

/* The company logo */

.footer-distributed .footer-left img{
  width: 30%;
}

.footer-distributed h3 span{
  color:  #e0ac1c;
}

/* Footer links */

.footer-distributed .footer-links{
  color:  #ffffff;
  margin: 20px 0 12px;
}

.footer-distributed .footer-links a{
  display:inline-block;
  line-height: 1.8;
  text-decoration: none;
  color:  inherit;
}

.footer-distributed .footer-company-name{
  color:  #8f9296;
  font-size: 14px;
  font-weight: normal;
  margin: 0;
}

/* Footer Center */

.footer-distributed .footer-center{
  width: 35%;
}


.footer-distributed .footer-center i{
  background-color:  #33383b;
  color: #ffffff;
  font-size: 25px;
  width: 38px;
  height: 38px;
  border-radius: 50%;
  text-align: center;
  line-height: 42px;
  margin: 10px 15px;
  vertical-align: middle;
}

.footer-distributed .footer-center i.fa-envelope{
  font-size: 17px;
  line-height: 38px;
}

.footer-distributed .footer-center p{
  display: inline-block;
  color: #ffffff;
  vertical-align: middle;
  margin:0;
}

.footer-distributed .footer-center p span{
  display:block;
  font-weight: normal;
  font-size:14px;
  line-height:2;
}

.footer-distributed .footer-center p a{
  color:  #e0ac1c;
  text-decoration: none;;
}


/* Footer Right */

.footer-distributed .footer-right{
  width: 30%;
}

.footer-distributed .footer-company-about{
  line-height: 20px;
  color:  #92999f;
  font-size: 13px;
  font-weight: normal;
  margin: 0;
}

.footer-distributed .footer-company-about span{
  display: block;
  color:  #ffffff;
  font-size: 18px;
  font-weight: bold;
  margin-bottom: 20px;
}

.footer-distributed .footer-icons{
  margin-top: 25px;
}

.footer-distributed .footer-icons a{
  display: inline-block;
  width: 35px;
  height: 35px;
  cursor: pointer;
  background-color:  #33383b;
  border-radius: 2px;

  font-size: 20px;
  color: #ffffff;
  text-align: center;
  line-height: 35px;

  margin-right: 3px;
  margin-bottom: 5px;
}

/* Here is the code for Responsive Footer */
/* You can remove below code if you don't want Footer to be responsive */


@media (max-width: 880px) {

  .footer-distributed .footer-left,
  .footer-distributed .footer-center,
  .footer-distributed .footer-right{
    display: block;
    width: 100%;
    margin-bottom: 40px;
    text-align: center;
  }

  .footer-distributed .footer-center i{
    margin-left: 0;
  }

}
    </style>
</head>
<body>
    <nav style="background-color: #0B2035;height:100px;">
    <div class="nav-wrapper">
      <ul id="nav-mobile" class="left hide-on-med-and-down">
        <li><a href="index.php" style="font-size: 50px;text-decoration:none;">BillShop</a></li>
      </ul>
      <a href="index.php" class="brand-logo center"><img src="billsblack.png" alt="Bills" width='56%' height='56%'/></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="index.php" title="Home" style="text-decoration: none;font-size: 20px;">Home</a></li>
        <li><a href="viewCart.php" title="Shopping Cart" style="text-decoration: none;font-size: 20px;">Shopping Cart</a></li>
        <?php
        if(!empty($_SESSION['UserID'])){
          ?>
          <li class="dropdown" style="list-style-type: none;">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="text-decoration:none;font-size: 20px;">Hello @ <?php echo $_SESSION['UserID']; ?> !
          </a>
          <ul class="dropdown-menu" role="menu" style="list-style-type: none;">
            <li><a href="admin/logout.php" style="color:black;list-style-type: none;font-size: 20px;">Log Out</a></li>
          </ul>
        </li>
        <?php
          }else{
            ?>
            <li><a href="./admin/login.php" title="Login" style="text-decoration: none;font-size: 20px;">Sign In</a></li>
            <?php
          }
          ?>
      </ul>
    </div>
  </nav>
      <nav style="background-color: white;height:60px;padding-left: 200px;">
    <div class="nav-wrapper">
      <ul id="nav-mobile" class="hide-on-med-and-down">
        <li><a href="newin.php" style="color:black;font-size:20px;">NEW IN</a></li>
        <li><a href="collection.php" style="color:black;font-size:20px;padding-left: 65px;">COLLECTION</a></li>
        <li><a href="active.php" style="color:black;font-size:20px;padding-left: 65px;">ACTIVE WEAR</a></li>
        <li><a href="lounge.php" style="color:black;font-size:20px;padding-left: 65px;">LOUNGEWEAR</a></li>
        <li><a href="tracks.php" style="color:black;font-size:20px;padding-left: 65px;">TRACKSUIT</a></li>
        <li><a href="sales.php" style="color:red;font-size:20px;padding-left: 65px;">SALE</a></li>
      </ul>
    </div>
  </nav>
<!-- <ul>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Hello <?php echo $_SESSION['UserID']; ?> !
  <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li><a href="admin/change_password.php" style="color:black;">Change Password</a></li>
    <li><a href="admin/logout.php" style="color:black;">Log Out</a></li>
  </ul>
</li>
</ul> -->
<div class="container">
    <h1>Order Status</h1>
    <script>
    swal("Order Placed!", "Your order will be available after 30mins!", "success");
    </script>
    <p>Your order has submitted successfully. Order ID is #<?php echo $_GET['id']; ?></p>
    <p>Kindly wait for the Browser to complete loading for you to pay</p>
</div>
<iframe src="<?php echo $iframe_src;?>" width="100%" height="700px"  scrolling="no" frameBorder="0">
    <p>Browser unable to load iFrame</p>
</iframe> 

    <footer class="footer-distributed" style="background-color:#0B2035;">

      <div class="footer-left">
          <img src="billsblack.png">
        <h3>About<span>BillShop</span></h3>

        <p class="footer-links">
          <a href="index.php">Home</a>
          |
          <a href="newin.php">Latest Products</a>
          |
          <a href="countdown.php">Super Bowl LV Offers</a>
        </p>

        <p class="footer-company-name">© 2020 BillShop. Ltd.</p>
      </div>

      <div class="footer-center">
<!--         <div>
          <i class="fa fa-map-marker"></i>
            <p><span>309 - Rupa Solitaire,
             Bldg. No. A - 1, Sector - 1</span>
            Mahape, Navi Mumbai - 400710</p>
        </div> -->

        <div>
          <i class="fa fa-phone"></i>
          <p>+254 123456789</p>
        </div>
        <div>
          <i class="fa fa-envelope"></i>
          <p><a href="mailto:support@eduonix.com">support@billshop.com</a></p>
        </div>
      </div>
      <div class="footer-right">
        <p class="footer-company-about">
          <span>About the Supermarket Franchise</span>
          We offer all your products under one roof.</p>
        <div class="footer-icons">
          <a href="#"><i class="fa fa-windows"></i></a>
          <a href="#"><i class="fa fa-twitter"></i></a>
          <a href="#"><i class="fa fa-instagram"></i></a>
          <a href="#"><i class="fa fa-linkedin"></i></a>
          <a href="#"><i class="fa fa-youtube"></i></a>
        </div>
      </div>
    </footer>
</body>
</html> 